# Version 0.1

## prefix for input data dirs
miseq_output: /data/Genomics/Upcoming_MiSeq_Runs
igv_output: /grid/home/nbourgeois/igv_data

## directories with pacbio data
input_data_dirs:
  D1: [dir_1]
  D2: [dir_2]

use_default_sheets: True

## samples in corresponding directories, only fill if use default is false
sample_sheets:
  S1: [sample_sheet_1]
  S2: [sample_sheet_2]

#sort by number of mutations wanted in tsv output
m_num: [number (int)]

# reference fasta file
reference: /reference/location/file.fa

# Methods
ampliseq: False 
snp_calling: False
only_fastq: True


# misc flags
bcl2fastq_flags:
bad_run: False
