
## prefix for input data dirs
miseq_output: /data/Genomics/Upcoming_MiSeq_Runs

## directories with pacbio data
input_data_dirs:
  D1: 220504_M05046_0157_000000000-KBM59

use_default_sheets: True

## samples in corresponding directories, only fill if use default is false
sample_sheets:

reference: /grid/data/JiraAnalyses/Misc/MISC-8/Analysis/references/Alu-OT-Block1-Top.fa
## downsampling percent (downsampling of input data)
# downsample_percent: 0.2

ampliseq: False 

snp_calling: True
coords_file: /grid/home/nbourgeois/snakemake-miseq/tests/220504_M05046_0157_000000000-KBM59/coords_file.txt

# misc flags
bcl2fastq_flags:
bad_run: False
